name: opentelemetry_logging
description: A simple library implementing sending logs to OpenTelemetry, supports gRPC and HTTP protocols.
version: 0.7.1
repository: https://github.com/NicolaVerbeeck/opentelemetry_logging_dart
topics:
  - logging
  - opentelemetry

environment:
  sdk: ^3.4.4

dependencies:
  fixnum: ^1.1.1
  http: ^1.4.0

dev_dependencies:
  lints: ^4.0.0
  mocktail: ^1.0.4
  test: ^1.24.0

